@echo off
setlocal

cd /d "%~dp0"

set "PATCH_ROOT=%cd%"
set "GAME_DIR=%PATCH_ROOT%"
set "SCRIPT_PATH=%PATCH_ROOT%\scripts\apply_korean_patch.ps1"
set "MANIFEST_PATH=%GAME_DIR%\KOR_PATCH_INSTALL_MANIFEST.txt"

if not exist "%SCRIPT_PATH%" (
    echo [ERROR] 필수 파일이 없습니다: scripts\apply_korean_patch.ps1
    goto :fail
)

call :check_required "%GAME_DIR%"
if errorlevel 1 (
    echo.
    echo 필요한 게임 아카이브를 찾지 못했습니다:
    echo   %GAME_DIR%
    echo.
    set /p "GAME_DIR=게임 폴더 경로를 입력하세요: "
    set "GAME_DIR=%GAME_DIR:"=%"
    if "%GAME_DIR%"=="" (
        echo [ERROR] 게임 폴더 경로가 비어 있습니다.
        goto :fail
    )
    if not exist "%GAME_DIR%" (
        echo [ERROR] 게임 폴더가 존재하지 않습니다: %GAME_DIR%
        goto :fail
    )
    call :check_required "%GAME_DIR%"
    if errorlevel 1 (
        echo [ERROR] 필요한 파일이 부족합니다.
        echo         필요 파일:
        echo           HD.HPF ^(게임 루트^)
        echo           CD1.HPF, CD2.HPF, CD3.HPF ^(게임 루트 또는 data/Data 폴더^)
        goto :fail
    )
)

set "ALLSUBS_HPF="
if exist "%GAME_DIR%\HD_ALLSUBS.HPF" (
    set "ALLSUBS_HPF=%GAME_DIR%\HD_ALLSUBS.HPF"
)
if not defined ALLSUBS_HPF if exist "%GAME_DIR%\data\HD_ALLSUBS.HPF" (
    set "ALLSUBS_HPF=%GAME_DIR%\data\HD_ALLSUBS.HPF"
)
if not defined ALLSUBS_HPF if exist "%GAME_DIR%\Data\HD_ALLSUBS.HPF" (
    set "ALLSUBS_HPF=%GAME_DIR%\Data\HD_ALLSUBS.HPF"
)

if /I "%KOR_SKIP_HASH_CHECK%"=="1" (
    echo [WARN] SHA256 아카이브 해시 검사를 건너뜁니다 ^(KOR_SKIP_HASH_CHECK=1^)
) else (
    echo [STEP] 아카이브 해시 검사 ^(SHA256^)
    call :verify_hashes "%GAME_DIR%" "%ALLSUBS_HPF%"
    if errorlevel 1 (
        goto :fail
    )
)

echo [STEP] KOREAN.HPF 생성
if defined ALLSUBS_HPF (
    powershell -NoProfile -ExecutionPolicy Bypass -File "%SCRIPT_PATH%" -GameDir "%GAME_DIR%" -AllSubsHpf "%ALLSUBS_HPF%"
) else (
    powershell -NoProfile -ExecutionPolicy Bypass -File "%SCRIPT_PATH%" -GameDir "%GAME_DIR%"
)
if errorlevel 1 (
    echo [ERROR] 패치 생성에 실패했습니다.
    goto :fail
)

if exist "%PATCH_ROOT%\runtime\" (
    echo [STEP] runtime 파일을 게임 폴더로 복사
    robocopy "%PATCH_ROOT%\runtime" "%GAME_DIR%" /E /R:1 /W:1 /NFL /NDL /NJH /NJS /NP >nul
    if errorlevel 8 (
        echo [ERROR] runtime 복사에 실패했습니다.
        goto :fail
    )
)

echo [STEP] 설치 매니페스트 기록
> "%MANIFEST_PATH%" (
    echo # The Last Express KOR install manifest
    echo # Generated by patch_and_install.bat
    echo REL^|KOREAN.HPF
)
if exist "%PATCH_ROOT%\runtime\" (
    powershell -NoProfile -ExecutionPolicy Bypass -Command ^
     "$ErrorActionPreference='Stop';" ^
     "$runtimePath=$env:PATCH_ROOT + '\runtime';" ^
     "$manifest=$env:MANIFEST_PATH;" ^
     "Get-ChildItem -Path $runtimePath -Recurse -File | ForEach-Object {" ^
     "  $rel=$_.FullName.Substring($runtimePath.Length).TrimStart('\');" ^
     "  Add-Content -Path $manifest -Value ('REL|' + $rel) -Encoding UTF8" ^
     "}"
    if errorlevel 1 (
        echo [WARN] runtime 파일 목록을 매니페스트에 완전히 기록하지 못했습니다.
    )
)

echo [STEP] 바탕화면 바로가기 생성
set "GAME_DIR_PS=%GAME_DIR%"
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
 "$ErrorActionPreference='Stop';" ^
 "$DesktopPath=[Environment]::GetFolderPath('Desktop');" ^
 "if([string]::IsNullOrWhiteSpace($DesktopPath)){throw '바탕화면 경로를 찾을 수 없습니다.'};" ^
 "$WshShell=New-Object -ComObject WScript.Shell;" ^
 "$Shortcut=$WshShell.CreateShortcut((Join-Path $DesktopPath 'The Last Express (KOR).lnk'));" ^
 "$GameDir=$env:GAME_DIR_PS;" ^
 "$TargetPath=(Join-Path $GameDir 'start.bat');" ^
 "if(-not (Test-Path $TargetPath)){throw '게임 폴더에서 start.bat를 찾을 수 없습니다.'};" ^
 "$Shortcut.TargetPath=$TargetPath;" ^
 "$Shortcut.WorkingDirectory=$GameDir;" ^
 "$IconPath=(Join-Path $GameDir 'lastexpress.ico');" ^
 "if(Test-Path $IconPath){$Shortcut.IconLocation=$IconPath};" ^
 "$Shortcut.Save()"
if errorlevel 1 (
    echo [WARN] 바탕화면 바로가기 생성에 실패했습니다.
) else (
    if exist "%GAME_DIR%\lastexpress.ico" (
        echo [INFO] lastexpress.ico 아이콘으로 바로가기를 생성했습니다.
    ) else (
        echo [WARN] lastexpress.ico를 찾을 수 없어 기본 아이콘이 사용됩니다.
    )
)
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
 "$DesktopPath=[Environment]::GetFolderPath('Desktop');" ^
 "if(-not [string]::IsNullOrWhiteSpace($DesktopPath)){" ^
 "  Add-Content -Path $env:MANIFEST_PATH -Value ('SHORTCUT|' + (Join-Path $DesktopPath 'The Last Express (KOR).lnk')) -Encoding UTF8" ^
 "}"

echo.
echo [DONE] 패치가 완료되었습니다.
echo        결과 파일: "%GAME_DIR%\KOREAN.HPF"
echo        실행 파일: "%GAME_DIR%\start.bat"
echo        제거 파일: "%GAME_DIR%\uninstall.bat"
pause
exit /b 0

:check_required
set "CHK_DIR=%~1"
if not exist "%CHK_DIR%\HD.HPF" exit /b 1
call :has_archive "%CHK_DIR%" "CD1.HPF"
if errorlevel 1 exit /b 1
call :has_archive "%CHK_DIR%" "CD2.HPF"
if errorlevel 1 exit /b 1
call :has_archive "%CHK_DIR%" "CD3.HPF"
if errorlevel 1 exit /b 1
exit /b 0

:has_archive
set "ARCH_DIR=%~1"
set "ARCH_NAME=%~2"
if exist "%ARCH_DIR%\%ARCH_NAME%" exit /b 0
if exist "%ARCH_DIR%\data\%ARCH_NAME%" exit /b 0
if exist "%ARCH_DIR%\Data\%ARCH_NAME%" exit /b 0
exit /b 1

:resolve_archive_path
set "ARCH_DIR=%~1"
set "ARCH_NAME=%~2"
set "%~3="
if exist "%ARCH_DIR%\%ARCH_NAME%" (
    set "%~3=%ARCH_DIR%\%ARCH_NAME%"
    exit /b 0
)
if exist "%ARCH_DIR%\data\%ARCH_NAME%" (
    set "%~3=%ARCH_DIR%\data\%ARCH_NAME%"
    exit /b 0
)
if exist "%ARCH_DIR%\Data\%ARCH_NAME%" (
    set "%~3=%ARCH_DIR%\Data\%ARCH_NAME%"
    exit /b 0
)
exit /b 1

:get_sha256
set "HASH_TARGET=%~1"
set "%~2="
for /f "usebackq delims=" %%H in (`powershell -NoProfile -ExecutionPolicy Bypass -Command "$p=$env:HASH_TARGET; if(Test-Path -LiteralPath $p){(Get-FileHash -Algorithm SHA256 -LiteralPath $p).Hash}" 2^>nul`) do (
    set "%~2=%%H"
)
set "HASH_TARGET="
if defined %~2 (
    exit /b 0
)
exit /b 1

:verify_archive_hash
set "TARGET_PATH=%~1"
set "DISPLAY_NAME=%~2"
set "EXPECTED_HASH=%~3"
call :get_sha256 "%TARGET_PATH%" ACTUAL_HASH
if errorlevel 1 (
    echo [WARN] "%DISPLAY_NAME%" 파일의 해시를 계산하지 못했습니다.
    echo        경로: "%TARGET_PATH%"
    set "HASH_MISMATCH=1"
    exit /b 1
)
if /I "%ACTUAL_HASH%"=="%EXPECTED_HASH%" (
    echo [OK] %DISPLAY_NAME% 해시 일치
    exit /b 0
)
echo [WARN] %DISPLAY_NAME% 해시 불일치
echo        경로      : "%TARGET_PATH%"
echo        기대값    : %EXPECTED_HASH%
echo        실제값    : %ACTUAL_HASH%
set "HASH_MISMATCH=1"
exit /b 1

:verify_hashes
set "VH_GAME_DIR=%~1"
set "VH_ALLSUBS=%~2"
set "HASH_MISMATCH=0"

call :verify_archive_hash "%VH_GAME_DIR%\HD.HPF" "HD.HPF" "0526D68F4D91212CD180CACCF8EB7F08AE1B8489FE0AC75AE60BDBC4A7D74C8C"
call :resolve_archive_path "%VH_GAME_DIR%" "CD1.HPF" CD1_PATH
if errorlevel 1 (
    echo [WARN] 해시 검사용 CD1.HPF를 찾지 못했습니다.
    set "HASH_MISMATCH=1"
) else (
    call :verify_archive_hash "%CD1_PATH%" "CD1.HPF" "A594136C5DC020EB9A444E3AA60E6A341998A93E590CC8AD7C6B976E0907F83A"
)
call :resolve_archive_path "%VH_GAME_DIR%" "CD2.HPF" CD2_PATH
if errorlevel 1 (
    echo [WARN] 해시 검사용 CD2.HPF를 찾지 못했습니다.
    set "HASH_MISMATCH=1"
) else (
    call :verify_archive_hash "%CD2_PATH%" "CD2.HPF" "F26293A597DBBDC6D782A1FAA38D9B33A786055A9C96F1D1A26CBFD6ED0EC6D7"
)
call :resolve_archive_path "%VH_GAME_DIR%" "CD3.HPF" CD3_PATH
if errorlevel 1 (
    echo [WARN] 해시 검사용 CD3.HPF를 찾지 못했습니다.
    set "HASH_MISMATCH=1"
) else (
    call :verify_archive_hash "%CD3_PATH%" "CD3.HPF" "909542B8CDF3FFC58016FEF757858F9A4DF48D0E6A3DEBC3C873BDAB551E10BA"
)

if defined VH_ALLSUBS (
    call :verify_archive_hash "%VH_ALLSUBS%" "HD_ALLSUBS.HPF" "F7FCC14E87731BAB2EC5A02E5634DD3189A46D0D002636560FFB51E9F5493F42"
)

if "%HASH_MISMATCH%"=="1" (
    echo.
    echo [WARN] 하나 이상의 아카이브 해시가 기대값과 다릅니다.
    choice /C YN /N /M "그래도 계속 진행할까요? [Y/N]: "
    if errorlevel 2 (
        exit /b 1
    )
)
exit /b 0

:fail
echo.
echo [FAILED] 실패했습니다.
echo [HINT] 이 패처는 이미 PowerShell ExecutionPolicy Bypass로 실행됩니다.
echo [HINT] 계속 실패하면 아래를 확인하세요:
echo        1) ZIP을 Program Files가 아닌 쓰기 가능한 폴더에 압축 해제
echo        2) ZIP/파일 우클릭 후 "차단 해제" 선택
echo        3) 최신 릴리즈 ZIP을 다시 압축 해제 후 재실행
pause
exit /b 1
